DELETE http://localhost:3003/api/blogs/658df0b9b18b52203fe24acd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZyYW5jaXNjbyIsImlkIjoiNjU4ZGUzYTQ4NTJmMzE0ZjIwNzFiYWU5IiwiaWF0IjoxNzAzNzk5ODAxfQ.ZBM79uGGChizlMFDtzfmnUNkElu87HpgB8Y8ASN2IsY